<?php
/**
 * Encapsulates all data generated by a controller in response to a Request
 */
class Jaded_Response
{
	protected $aAssigns = array();
	protected $aHeaders = array();
	protected $aTemplates = array();

	////////////////////////////////////////////////////////////////////////////////
	// PUBLIC /////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////////////////

	/**
	 * Assign a named value
	 * @param string $sName
	 * @param mixed $mValue
	 */
	public function assign($sName, $mValue)
	{
		$this->aAssigns[$sName] = $mValue;
	}

	/**
	 * Retrieve all assigned elements in this response
	 * @return array
	 */
	public function getAssigns()
	{
		return $this->aAssigns;
	}

	/**
	 * Assign a header
	 * @param string $sName
	 * @param string $sValue
	 */
	public function header($sName, $sValue)
	{
		$this->aHeaders[$sName] = $sValue;
	}

	/**
	 * Retrieve all assigned headers in this response
	 * @return array
	 */
	public function getHeaders()
	{
		return $this->aHeaders;
	}

	/**
	 * Redirect to another application uri
	 * @param string $sUri
	 */
	public function redirect($sUri)
	{
		$this->header('Location', $sUri);
	}

	/**
	 * Is this response carrying a redirect?
	 * @return boolean
	 */
	public function isRedirected()
	{
		return !empty($this->aHeaders['Location']);
	}

	/**
	 * Retrieve a named template
	 * @param string $sName
	 * @return string
	 */
	public function getTemplate($sName)
	{
		return isset($this->aTemplates[$sName]) ? $this->aTemplates[$sName] : null;
	}

	/**
	 * Set a named template
	 * @param string $sName
	 * @param string $sTemplate
	 */
	public function setTemplate($sName, $sTemplate)
	{
		$this->aTemplates[$sName] = $sTemplate;
	}
}
